services:
  - type: web
    name: ai-chatbot-hacknova
    env: node
    buildCommand: npm install && npm run build
    startCommand: vite preview --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
